pull_request_rules:
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
    actions:
      merge:
        method: merge

  - name: automatic merge for dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=get-release
    actions:
      merge:
        method: merge

  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success=get-release
    actions:
      merge:
        method: merge

  - name: automatic merge for Requires.io pull requests
    conditions:
      - title~=^\[requires.io\]
      - head~=^requires-io
      - check-success=get-release
    actions:
      merge:
        method: merge

  # https://docs.mergify.com/workflow/delete-head-branches/#prevent-deletion-for-dependent-branches
  - name: delete head branch after merge but not if other PRs depend on it
    conditions:
      - merged
    actions:
      delete_head_branch:
        force: false
